get_race_by_age_and_sex <- function(locality) {
  white_labels = combine_age_and_race("White Alone")
  black_labels = combine_age_and_race("Black or African American Alone")
  american_indian_labels = combine_age_and_race("American Indian and Alaskan Native Alone")
  asian_labels = combine_age_and_race("Asian Alone")
  hawaiian_labels = combine_age_and_race("Native Hawaiian and Other Pacific Islander Alone")
  other_race_labels = combine_age_and_race("Some Other Race Alone")
  two_or_more_race_labels = combine_age_and_race("Two or More Races")
  white_non_hispanic_labels = combine_age_and_race("White Alone, not Hispanic or Latino")
  hispanic_labels = combine_age_and_race("Hispanic or Latino")
  
  ages_by_race_white_raw = call_tidycensus(locality, "B01001A")
  ages_by_race_black_raw = call_tidycensus(locality, "B01001B")
  ages_by_race_american_indian_raw = call_tidycensus(locality, "B01001C")
  ages_by_race_asian_raw = call_tidycensus(locality, "B01001D")
  ages_by_race_hawaiian_raw = call_tidycensus(locality, "B01001E")
  ages_by_race_other_race_raw = call_tidycensus(locality, "B01001F")
  ages_by_race_two_or_more_race_raw = call_tidycensus(locality, "B01001G")
  ages_by_race_white_non_hispanic_raw = call_tidycensus(locality, "B01001H")
  ages_by_race_hispanic_raw = call_tidycensus(locality, "B01001I")
  
  ages_by_race_white_cleaned = clean_data(ages_by_race_white_raw, white_labels, "other")
  ages_by_race_black_cleaned = clean_data(ages_by_race_black_raw, black_labels, "other")
  ages_by_race_american_indian_cleaned = clean_data(ages_by_race_american_indian_raw, american_indian_labels, "other")
  ages_by_race_asian_cleaned = clean_data(ages_by_race_asian_raw, asian_labels, "other")
  ages_by_race_hawaiian_cleaned = clean_data(ages_by_race_hawaiian_raw, hawaiian_labels, "other")
  ages_by_race_other_race_cleaned = clean_data(ages_by_race_other_race_raw, other_race_labels, "other")
  ages_by_race_two_or_more_race_cleaned = clean_data(ages_by_race_two_or_more_race_raw, two_or_more_race_labels, "other")
  ages_by_race_white_non_hispanic_cleaned = clean_data(ages_by_race_white_non_hispanic_raw, white_non_hispanic_labels, "other")
  ages_by_race_hispanic_cleaned = clean_data(ages_by_race_hispanic_raw, hispanic_labels, "other")
  
  ages_by_race = rbind(ages_by_race_white_cleaned, ages_by_race_black_cleaned)
  ages_by_race = rbind(ages_by_race, ages_by_race_american_indian_cleaned)
  ages_by_race = rbind(ages_by_race, ages_by_race_asian_cleaned)
  ages_by_race = rbind(ages_by_race, ages_by_race_hawaiian_cleaned)
  ages_by_race = rbind(ages_by_race, ages_by_race_other_race_cleaned)
  ages_by_race = rbind(ages_by_race, ages_by_race_two_or_more_race_cleaned)
  ages_by_race = rbind(ages_by_race, ages_by_race_white_non_hispanic_cleaned)
  ages_by_race = rbind(ages_by_race, ages_by_race_hispanic_cleaned)
  return(ages_by_race)
}
